### ISSUE TITLE
Problems with Basic Checkout on Android

### ISSUE THREAD

**Issue by hjJunior** [mercadopago/px-android#1297]
I think this is same problem of #611 

I'm getting  same problem here, first of all I created manually on my server with my credentials for basic checkout client_id and secret, so I got the ID of checkout preference and put on my App

So after click on the button on Android I start this method

```java
new MercadoPagoCheckout.Builder(PUBLIC_KEY, CHECKOUT_PREFERENCE_ID)
  .build()
  .startPayment(MainActivity.this, REQUEST_CODE);
```

And constants values:
```
PUBLIC_KEY: 667069144398008
CHECKOUT_PREFERENCE_ID: 187081368-b89bb61d-71bb-4b11-9c33-b8a6b14fb0d2
````

I've tested this on simulator and physical device

```
- LG K10 (LGE LG-k430 Android 6.0, API 23) 
- Nexus 5X API 28 x86 (AVD)
```
- Android Studio 3.2.1
- Linux Ubuntu 18.0.4 x64

Using the version 4+

```gradle
implementation 'com.mercadopago.android.px:checkout:4.+'
````

So the execption I got is this:

```log
10-14 10:54:22.152 18237-18237/br.com.coderfox.testinmercadopago W/Calligraphy: Can't create asset from null. Make sure you have passed in the correct path and file name.
    java.lang.NullPointerException
        at android.graphics.FontFamily.nAddFontFromAsset(Native Method)
        at android.graphics.FontFamily.addFontFromAsset(FontFamily.java:77)
        at android.graphics.Typeface.createFromAsset(Typeface.java:267)
        at uk.co.chrisjenx.calligraphy.TypefaceUtils.load(TypefaceUtils.java:35)
        at com.mercadolibre.android.ui.font.TypefaceHelper.createTypeface(TypefaceHelper.java:56)
        at com.mercadolibre.android.ui.font.TypefaceHelper.setTypeface(TypefaceHelper.java:29)
        at com.mercadolibre.android.ui.widgets.MeliButton.configureButton(MeliButton.java:87)
        at com.mercadolibre.android.ui.widgets.MeliButton.<init>(MeliButton.java:79)
        at com.mercadolibre.android.ui.widgets.MeliButton.<init>(MeliButton.java:66)
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at android.view.LayoutInflater.createView(LayoutInflater.java:619)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
        at com.mercadopago.android.px.internal.features.ErrorActivity.onCreate(ErrorActivity.java:40)
        at android.app.Activity.performCreate(Activity.java:6272)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
        at android.app.ActivityThread.access$900(ActivityThread.java:157)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5530)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:734)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
```
![device-2018-10-14-105420](https://user-images.githubusercontent.com/10780132/46917668-f7dcea00-cf9f-11e8-86be-2a8e9d488f82.png)
![device-2018-10-14-105655](https://user-images.githubusercontent.com/10780132/46917669-f7dcea00-cf9f-11e8-89ab-890effe79836.png)

**Comment by zehemz** [comment]
Hi there,
That public key you're useing seems to not be valid.
You can get your public key on mercadopago's developers console.

The trace you placed is not related with the error message.

Please, check our example app, you can find some valid public keys.

**Comment by hjJunior** [comment]
I've changed my public key to:
`TEST-5a3399aa-fba2-40c8-b99a-7508f10320c2`

And I keep got the same, follow the complete log since click button

```log
10-14 11:30:19.958 26534-26534/br.com.coderfox.testinmercadopago I/ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
10-14 11:30:19.985 26534-26534/br.com.coderfox.testinmercadopago I/ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
10-14 11:30:19.999 26534-26676/br.com.coderfox.testinmercadopago I/[MALI][Gralloc]: [+]r_hnd(0xb9fb8b80), client(42), share_fd(52)
10-14 11:30:20.005 26534-26534/br.com.coderfox.testinmercadopago I/AudioManagerEx: AudioManagerEx created
10-14 11:30:20.274 26534-26534/br.com.coderfox.testinmercadopago I/Timeline: Timeline: Activity_launch_request id:br.com.coderfox.testinmercadopago time:161140962
10-14 11:30:20.335 26534-26534/br.com.coderfox.testinmercadopago D/PhoneWindowEx: [PWEx][generateLayout] setLGNavigationBarColor : colors=0xff000000
10-14 11:30:20.335 26534-26534/br.com.coderfox.testinmercadopago I/PhoneWindow: [setLGNavigationBarColor] color=0x ff000000
10-14 11:30:20.658 26534-26534/br.com.coderfox.testinmercadopago D/PhoneWindow: notifyNavigationBarColor, color=0x: ff000000, token: android.view.ViewRootImplAO$WEx@7725b36
10-14 11:30:20.673 26534-26676/br.com.coderfox.testinmercadopago D/mali_winsys: new_window_surface returns 0x3000
10-14 11:30:20.711 26534-26676/br.com.coderfox.testinmercadopago I/[MALI][Gralloc]: [+]r_hnd(0xba0870f8), client(42), share_fd(58)
10-14 11:30:20.731 26534-26676/br.com.coderfox.testinmercadopago I/[MALI][Gralloc]: [+]r_hnd(0xba04e640), client(42), share_fd(54)
10-14 11:30:20.734 26534-26534/br.com.coderfox.testinmercadopago V/ViewRootImpl: Contents drawing finished : br.com.coderfox.testinmercadopago/com.mercadopago.android.px.internal.features.CheckoutActivity
10-14 11:30:20.745 26534-26676/br.com.coderfox.testinmercadopago I/[MALI][Gralloc]: [+]r_hnd(0xb8f06808), client(42), share_fd(59)
10-14 11:30:20.779 26534-26676/br.com.coderfox.testinmercadopago I/[MALI][Gralloc]: [-]r_hnd(0xb9faf710), client(42), share_fd(50)
10-14 11:30:20.780 26534-26676/br.com.coderfox.testinmercadopago I/[MALI][Gralloc]: [-]r_hnd(0xb9fb8b80), client(42), share_fd(52)
10-14 11:30:20.783 26534-26676/br.com.coderfox.testinmercadopago I/[MALI][Gralloc]: [-]r_hnd(0xba03bbc0), client(42), share_fd(49)
10-14 11:30:20.784 26534-26676/br.com.coderfox.testinmercadopago D/OpenGLRenderer: endAllActiveAnimators on 0xba26e710 (RippleDrawable) with handle 0xba289360
10-14 11:30:32.074 26534-26534/br.com.coderfox.testinmercadopago I/Timeline: Timeline: Activity_launch_request id:br.com.coderfox.testinmercadopago time:161152761
10-14 11:30:32.116 26534-26534/br.com.coderfox.testinmercadopago D/PhoneWindowEx: [PWEx][generateLayout] setLGNavigationBarColor : colors=0xff000000
10-14 11:30:32.116 26534-26534/br.com.coderfox.testinmercadopago I/PhoneWindow: [setLGNavigationBarColor] color=0x ff000000
10-14 11:30:32.150 26534-26534/br.com.coderfox.testinmercadopago W/Calligraphy: Can't create asset from null. Make sure you have passed in the correct path and file name.
    java.lang.NullPointerException
        at android.graphics.FontFamily.nAddFontFromAsset(Native Method)
        at android.graphics.FontFamily.addFontFromAsset(FontFamily.java:77)
        at android.graphics.Typeface.createFromAsset(Typeface.java:267)
        at uk.co.chrisjenx.calligraphy.TypefaceUtils.load(TypefaceUtils.java:35)
        at com.mercadolibre.android.ui.font.TypefaceHelper.createTypeface(TypefaceHelper.java:56)
        at com.mercadolibre.android.ui.font.TypefaceHelper.setTypeface(TypefaceHelper.java:29)
        at com.mercadolibre.android.ui.widgets.MeliButton.configureButton(MeliButton.java:87)
        at com.mercadolibre.android.ui.widgets.MeliButton.<init>(MeliButton.java:79)
        at com.mercadolibre.android.ui.widgets.MeliButton.<init>(MeliButton.java:66)
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at android.view.LayoutInflater.createView(LayoutInflater.java:619)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
        at com.mercadopago.android.px.internal.features.ErrorActivity.onCreate(ErrorActivity.java:40)
        at android.app.Activity.performCreate(Activity.java:6272)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
        at android.app.ActivityThread.access$900(ActivityThread.java:157)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5530)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:734)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
10-14 11:30:32.176 26534-26534/br.com.coderfox.testinmercadopago D/PhoneWindow: notifyNavigationBarColor, color=0x: ff000000, token: android.view.ViewRootImplAO$WEx@195b5f7
10-14 11:30:32.206 26534-26676/br.com.coderfox.testinmercadopago D/mali_winsys: new_window_surface returns 0x3000
10-14 11:30:32.231 26534-26676/br.com.coderfox.testinmercadopago I/[MALI][Gralloc]: [+]r_hnd(0xba3cc6e8), client(42), share_fd(56)
10-14 11:30:32.258 26534-26676/br.com.coderfox.testinmercadopago I/[MALI][Gralloc]: [+]r_hnd(0xb9f6bbf0), client(42), share_fd(57)
10-14 11:30:32.260 26534-26534/br.com.coderfox.testinmercadopago V/ViewRootImpl: Contents drawing finished : br.com.coderfox.testinmercadopago/com.mercadopago.android.px.internal.features.ErrorActivity
10-14 11:30:32.265 26534-26676/br.com.coderfox.testinmercadopago I/[MALI][Gralloc]: [-]r_hnd(0xba0870f8), client(42), share_fd(58)
10-14 11:30:32.266 26534-26676/br.com.coderfox.testinmercadopago I/[MALI][Gralloc]: [-]r_hnd(0xba04e640), client(42), share_fd(54)
10-14 11:30:32.270 26534-26676/br.com.coderfox.testinmercadopago I/[MALI][Gralloc]: [-]r_hnd(0xb8f06808), client(42), share_fd(59)
10-14 11:30:32.277 26534-26534/br.com.coderfox.testinmercadopago I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@c112df6 time:161152965
10-14 11:30:32.279 26534-26534/br.com.coderfox.testinmercadopago I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@a2e035b time:161152966
````

**Comment by zehemz** [comment]
The log says that you can not load a null font. Does the app crash?

Are you useing custom fonts / calligraphy?

Can you please provide a full code sample?

Does the preference have an email inside payer info or have you just copy a preference through the web?

**Comment by hjJunior** [comment]
Guy, I peg your pardon, It's just a careless mistake, on my setup of enviroment variables I've added a empty space inside the string

````diff
- private static final String PUBLIC_KEY = " TEST-5a3399aa-fba2-40c8-b99a-7508f10320c2";
+ private static final String PUBLIC_KEY = "TEST-5a3399aa-fba2-40c8-b99a-7508f10320c2";
````

But I tried to go ahead, After chose to create new credit card or even "Boleto bancario" I got same screen on finish

**Comment by marianolop22** [comment]
Hi! having the same issue, all the values are perfect, a really don't know how to solve this problem.
I'm using the same code posted in you web.
https://www.mercadopago.com.ar/developers/es/guides/payments/mobile-checkout/receive-payments/

**Comment by marianolop22** [comment]
If I use the same example but library 4.5.2 the checkout works great

**Comment by AlyssonPHN** [comment]
where to get the CHECKOUT_PREFERENCE_ID id?

**Comment by dekaru** [comment]
> If I use the same example but library 4.5.2 the checkout works great

Thanks @marianolop22 , I can confirm that I was getting the exact same error and that using this version fixed it.

> The trace you placed is not related with the error message.

You're right @zehemz : it is not and yet that's what we get upon a clean install from the sample app. Further on:

> Does the app crash?

No, please read @hjJunior 's description. 

> Are you using custom fonts / calligraphy?

No, it's a clean clone. Didn't change a simple thing. 

> Can you please provide a full code sample?

Sure, you can download it from: https://github.com/mercadopago/px-android/
