### ISSUE TITLE
ErrorActivity line 37

### ISSUE THREAD

**Issue by bolds07** [mercadopago/px-android#1498]
error happening at runtime on real devices

Device
Brand: LGE
Model: Nexus 4
Orientation: Portrait
RAM free: 1.08 GB
Disk free: 418.1 MB
Operating System
Version: 6.0.1
Orientation: Portrait
Rooted: No
Crash
Date: Jan 1, 2019, 3:12:07 PM
App version: 4.3.5 (178)

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tomatedigital.instagramgiveawaywinner/com.mercadopago.android.px.internal.features.ErrorActivity}: android.view.InflateException: Binary XML file line #18: Binary XML file line #18: Error inflating class ImageView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2419)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2479)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5420)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

Caused by android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f0801b2
       at android.content.res.Resources.getResourceName(Resources.java:2235)
       at android.content.res.Resources.loadDrawableForCookie(Resources.java:2602)
       at android.content.res.Resources.loadDrawable(Resources.java:2540)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:870)
       at android.widget.ImageView.(ImageView.java:152)
       at android.widget.ImageView.(ImageView.java:140)
       at android.support.v7.widget.AppCompatImageView.(SourceFile:71)
       at android.support.v7.widget.AppCompatImageView.(SourceFile:67)
       at android.support.v7.app.AppCompatViewInflater.createImageView(SourceFile:181)
       at android.support.v7.app.AppCompatViewInflater.createView(SourceFile:105)
       at android.support.v7.app.AppCompatDelegateImplV9.createView(SourceFile:1035)
       at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(SourceFile:1092)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(SourceFile:287)
       at android.support.v7.app.AppCompatActivity.setContentView(SourceFile:139)
       at com.mercadopago.android.px.internal.features.ErrorActivity.onCreate(SourceFile:37)
       at android.app.Activity.performCreate(Activity.java:6280)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2372)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2479)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5420)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by zehemz** [comment]
We can't reproduce the issue. ErrorActivity is a generic message activity. Could you tell us more information about this bug. We have 0 incidences in our inhouse distribution of this checkout.
