### ISSUE TITLE
java.lang.NoSuchMethodError: No static method with(Landroid/content/Context;)Lcom/squareup/picasso/Picasso;

### ISSUE THREAD

**Issue by backjeff** [mercadopago/px-android#1546]
Conflicts with project using Picasso 2.71828

j```
ava.lang.NoSuchMethodError: No static method with(Landroid/content/Context;)Lcom/squareup/picasso/Picasso; in class Lcom/squareup/picasso/Picasso; or its super classes (declaration of 'com.squareup.picasso.Picasso' appears in /data/app/MY-APP-HERE/split_lib_dependencies_apk.apk:classes2.dex)
        at com.mercadopago.android.px.internal.features.paymentresult.components.IconRenderer.renderIconFromResource(IconRenderer.java:64)
        at com.mercadopago.android.px.internal.features.paymentresult.components.IconRenderer.render(IconRenderer.java:33)
        at com.mercadopago.android.px.internal.features.paymentresult.components.IconRenderer.render(IconRenderer.java:18)
        at com.mercadopago.android.px.internal.view.Renderer.render(Renderer.java:35)
        at com.mercadopago.android.px.internal.features.paymentresult.components.HeaderRenderer.render(HeaderRenderer.java:42)
        at com.mercadopago.android.px.internal.features.paymentresult.components.HeaderRenderer.render(HeaderRenderer.java:18)
        at com.mercadopago.android.px.internal.view.Renderer.render(Renderer.java:35)
        at com.mercadopago.android.px.internal.features.paymentresult.components.PaymentResultRenderer.render(PaymentResultRenderer.java:28)
        at com.mercadopago.android.px.internal.features.paymentresult.components.PaymentResultRenderer.render(PaymentResultRenderer.java:14)
        at com.mercadopago.android.px.internal.view.Renderer.render(Renderer.java:35)
        at com.mercadopago.android.px.internal.view.ComponentManager.render(ComponentManager.java:30)
        at com.mercadopago.android.px.internal.view.ComponentManager.onProps(ComponentManager.java:64)
        at com.mercadopago.android.px.internal.features.paymentresult.PaymentResultPropsMutator.notifyPropsChanged(PaymentResultPropsMutator.java:60)
        at com.mercadopago.android.px.internal.features.paymentresult.PaymentResultPresenter.checkGetInstructions(PaymentResultPresenter.java:179)
        at com.mercadopago.android.px.internal.features.paymentresult.PaymentResultPresenter.onValidStart(PaymentResultPresenter.java:84)
        at com.mercadopago.android.px.internal.features.paymentresult.PaymentResultPresenter.initialize(PaymentResultPresenter.java:52)
        at com.mercadopago.android.px.internal.features.paymentresult.PaymentResultActivity.onResume(PaymentResultActivity.java:150)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1269)
        at android.app.Activity.performResume(Activity.java:6783)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3406)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3469)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2732)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by zehemz** [comment]
Hi @backjeff,
Version 2.7 (2018-03-07) is a pre release for 3.0 that is not fully compatible with version 2 last stable backwards compatible version.

https://github.com/square/picasso/blob/master/CHANGELOG.md

In our production environments we will keep using v2.5.2 version.

**Comment by AxelESSONO** [comment]
Hi, I am beginner, I have a problem when I use Picasso version 2.5.2
   
  java.lang.NoSuchMethodError: No static method with(Landroid/content/Context;)Lcom/squareup/picasso/Picasso; in class Lcom/squareup/picasso/Picasso; or its super classes (declaration of 'com.squareup.picasso.Picasso' appears in /data/app/com.obiangetfils.kermashop-oi-9GN_TavpBHekxheeFUg==/base.apk)
        at com.daimajia.slider.library.SliderTypes.BaseSliderView.bindEventAndShow(BaseSliderView.java:210)
        at com.daimajia.slider.library.SliderTypes.DefaultSliderView.getView(DefaultSliderView.java:25)
        at com.daimajia.slider.library.SliderAdapter.instantiateItem(SliderAdapter.java:81)
        at com.daimajia.slider.library.Tricks.InfinitePagerAdapter.instantiateItem(InfinitePagerAdapter.java:54)
        at com.daimajia.slider.library.Tricks.ViewPagerEx.addNewItem(ViewPagerEx.java:848)
        at com.daimajia.slider.library.Tricks.ViewPagerEx.populate(ViewPagerEx.java:998)
        at com.daimajia.slider.library.Tricks.ViewPagerEx.populate(ViewPagerEx.java:930)
        at com.daimajia.slider.library.Tricks.ViewPagerEx.onMeasure(ViewPagerEx.java:1453)
        at android.view.View.measure(View.java:26415)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
        at android.view.View.measure(View.java:26415)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
        at android.view.View.measure(View.java:26415)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
        at android.view.View.measure(View.java:26415)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:26415)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:26415)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:26415)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at com.google.android.material.appbar.AppBarLayout.onMeasure(AppBarLayout.java:264)
        at android.view.View.measure(View.java:26415)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:733)
        at com.google.android.material.appbar.AppBarLayout$BaseBehavior.onMeasureChild(AppBarLayout.java:1161)
        at com.google.android.material.appbar.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:842)
        at com.google.android.material.appbar.AppBarLayout$BaseBehavior.onMeasureChild(AppBarLayout.java:869)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:803)
        at android.view.View.measure(View.java:26415)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:26415)
        at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1119)
        at android.view.View.measure(View.java:26415)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
2020-03-27 13:27:56.453 12627-12627/com.obiangetfils.kermashop E/AndroidRuntime:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:26415)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:26415)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:26415)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:26415)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:26415)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1009)
        at android.view.View.measure(View.java:26415)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3578)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2321)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2613)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2169)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8933)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:996)
        at android.view.Choreographer.doCallbacks(Choreographer.java:794)
        at android.view.Choreographer.doFrame(Choreographer.java:729)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7811)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

**Comment by cgaggino** [comment]
Hi AxelESSONO, how are you?

We use Picasso 2.5.2 as well, so you should not have any problem, seems like other lib you are using has a dependency with a higher version of picasso, you can check it running the gradle dependency task

Do not doubt to come back to us again if you need any further help
