### ISSUE TITLE
Can't finish checkout due "W/Calligraphy: Can't create asset from null. Make sure you have passed in the correct path and file name"

### ISSUE THREAD

**Issue by backjeff** [mercadopago/px-android#1549]
- Android N
- classpath 'com.android.tools.build:gradle:3.3.0'
- currency_id = "BRL"

**App Gradle**
`implementation 'com.mercadopago.android.px:checkout:4.0.+'`

**In MainActivity im calling**
```
private void startMercadoPagoCheckout(final String checkoutPreferenceId) {
   new MercadoPagoCheckout.Builder("TEST-PUBLIC-KEY", checkoutPreferenceId).build()
                    .startPayment(MainActivity.this, REQUEST_CODE);
}
```

After fill CPF, this screen appears

![captura de tela de 2019-02-05 17-46-38](https://user-images.githubusercontent.com/6492543/52300053-165f5a80-296e-11e9-8bcb-aaf5946996a0.png)

And the logCat throws

```
W/Calligraphy: Can't create asset from null. Make sure you have passed in the correct path and file name.
    java.lang.NullPointerException
        at android.graphics.FontFamily.nAddFontFromAsset(Native Method)
        at android.graphics.FontFamily.addFontFromAsset(FontFamily.java:89)
        at android.graphics.Typeface.createFromAsset(Typeface.java:198)
        at uk.co.chrisjenx.calligraphy.TypefaceUtils.load(TypefaceUtils.java:35)
        at com.mercadolibre.android.ui.font.TypefaceHelper$1.createTypeface(TypefaceHelper.java:58)
        at com.mercadolibre.android.ui.font.TypefaceHelper$1.setTypeface(TypefaceHelper.java:28)
        at com.mercadolibre.android.ui.font.TypefaceHelper.setTypeface(TypefaceHelper.java:82)
        at com.mercadolibre.android.ui.widgets.MeliButton.configureButton(MeliButton.java:87)
        at com.mercadolibre.android.ui.widgets.MeliButton.<init>(MeliButton.java:79)
        at com.mercadolibre.android.ui.widgets.MeliButton.<init>(MeliButton.java:66)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at android.view.LayoutInflater.createView(LayoutInflater.java:645)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at com.mercadopago.android.px.internal.features.ErrorActivity.onCreate(ErrorActivity.java:40)
        at android.app.Activity.performCreate(Activity.java:6679)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

```

**Comment by marianolop22** [comment]
Hi! having the same issue, it's impossible to implement this. Using the same code in you web. Is there a way to solve this???

**Comment by marianolop22** [comment]
If I use the same example but library 4.5.2 the checkout works great
With the latest version it's not working
