### ISSUE TITLE
Not complete response from Intent data

### ISSUE THREAD

**Issue by cinder92** [mercadopago/px-android#1598]
Hello, Intent from `onActivityResult` is only returning this `{"extra_result_code":7}` it does not matter which payment method i choose, always is same response

```
public void onActivityResult(Activity activity, int requestCode, int resultCode, Intent data) {

    JSONObject json = new JSONObject();
    Set<String> keys = data.getExtras().keySet();

    for (String key : keys) {
      try {
        // json.put(key, bundle.get(key)); see edit below
        json.put(key, JSONObject.wrap(data.getExtras().get(key)));
      } catch(JSONException e) {
        //Handle exception here
      }
    }

      Log.d("pago con Activity => ", json.toString() );

      if (promise == null || requestCode != REQUEST_CODE || data == null) {
      return;
    }

    if (resultCode == MercadoPagoCheckout.PAYMENT_RESULT_CODE) {
        if(data != null && data.getStringExtra(MP_PAYMENT_DATA) != null) {
          final PaymentData paymentData = this.getData(data, MP_PAYMENT_DATA, PaymentData.class);
          final WritableMap paymentDataMap = this.paymentDataToMap(paymentData);

          //Resolve values as map
          promise.resolve(paymentDataMap);
        }
    }
    else if (resultCode == MercadoPagoCheckout.PAYMENT_RESULT_CODE) {
        if(data != null && data.getStringExtra(MP_PAYMENT) != null) {
          final Payment payment = this.getData(data, MP_PAYMENT, Payment.class);
          final WritableMap paymentMap = this.paymentToMap(payment);

          //Resolve values as map
          promise.resolve(paymentMap);
        }
    }
    else if (resultCode == RESULT_CANCELED) {
      if (data != null && data.getStringExtra(MP_PAYMENT_ERROR) != null) {
        final MercadoPagoError mercadoPagoError = this.getData(data, MP_PAYMENT_ERROR, MercadoPagoError.class);
        final Throwable wrappedError = new Throwable(mercadoPagoError.getErrorDetail());

        //Reject promise on MPError, and bubble error data to react-native
        promise.reject(PAYMENT_ERROR, "Payment failed.", wrappedError);
      }
      else {
        //Reject promise on user cancellation
        promise.reject(PAYMENT_CANCELLED, "Payment was cancelled by the user.");
      }
    }

    promise = null;
    //this.clearCurrentPromise();
  }
```

any idea whats happening, please?

**Comment by zehemz** [comment]
@cinder92  we will look at.

@matiasromar @cgaggino can you look at this please?

**Comment by cinder92** [comment]
@zehemz any update on this?

**Comment by cinder92** [comment]
this is my preferenceId and publicKey testing

`https://api.mercadopago.com/checkout/preferences/241794410-bfd8446e-f49a-4b65-b421-7c0e7fa656e4?access_token=TEST-5728883045341808-022807-f931bf278cdadba9b91c49100928226a-241794410#json`

**Comment by jdnichollsc** [comment]
I'm getting the same response: `{"extra_result_code":7}`

I can see the following error:
```
2019-03-07 01:03:21.555 15644-15644/com.example W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@abdaf9f
2019-03-07 01:03:21.563 15644-15644/com.example W/Bundle: Attempt to cast generated internal exception:
    java.lang.ClassCastException: java.math.BigDecimal cannot be cast to java.lang.String
        at android.os.BaseBundle.getString(BaseBundle.java:1158)
        at android.content.Intent.getStringExtra(Intent.java:8111)
        at com.mercadopago.android.px.internal.features.paymentresult.PaymentResultActivity.getActivityParameters(PaymentResultActivity.java:203)
        at com.mercadopago.android.px.internal.features.paymentresult.PaymentResultActivity.onCreate(PaymentResultActivity.java:112)
        at android.app.Activity.performCreate(Activity.java:7326)
        at android.app.Activity.performCreate(Activity.java:7317)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3066)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3229)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6981)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

Gracias de antemano!

**Comment by cgaggino** [comment]
Hi @cinder92, 

You are seeing only that in the log because when you do:
```
json.put(key, JSONObject.wrap(data.getExtras().get(key)));
```
JSONObject.wrap returns null over the Payment parameter which key is MercadoPagoCheckout.EXTRA_PAYMENT_RESULT

However, to get Payment result you can do something like this:
```
if (resultCode == MercadoPagoCheckout.PAYMENT_RESULT_CODE) {
        final Payment payment = (Payment) data.getSerializableExtra(MercadoPagoCheckout.EXTRA_PAYMENT_RESULT);
        // do something
else if (resultCode == RESULT_CANCELED) {
        // do something else
}
```

**Comment by jdnichollsc** [comment]
It's working as expected now :)

**Comment by cgaggino** [comment]
Hi @jdnichollsc,

In regard of your error, it seems like you are using version 4.0.3 or older. I suggest you to upgrade to a newer version like 4.7.2

Regards.
