### ISSUE TITLE
Attempt to invoke virtual method 'java.lang.String com.mercadopago.android.px.model.PaymentMethod.getId()' on a null object reference

### ISSUE THREAD

**Issue by bolds07** [mercadopago/px-android#1601]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.mercadopago.android.px.model.PaymentMethod.getId()' on a null object reference
       at com.mercadopago.android.px.tracking.internal.model.AvailableMethod.from(SourceFile:45)
       at com.mercadopago.android.px.tracking.internal.events.FrictionEventTracker.with(SourceFile:33)
       at com.mercadopago.android.px.internal.features.guessing_card.GuessingCardPresenter.validateCardNumber(SourceFile:667)
       at com.mercadopago.android.px.internal.features.guessing_card.GuessingCardActivity.validateCurrentEditText(SourceFile:1164)
       at com.mercadopago.android.px.internal.features.guessing_card.GuessingCardActivity.onNextKey(SourceFile:868)
       at com.mercadopago.android.px.internal.features.guessing_card.GuessingCardActivity$3.onEditorAction(SourceFile:492)
       at android.widget.TextView.onEditorAction(TextView.java:6292)
       at com.android.internal.widget.EditableInputConnection.performEditorAction(EditableInputConnection.java:138)
       at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:360)
       at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6923)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)

**Comment by matiasromar** [comment]
Hi @bolds07 
Which is the px-android's version that you are running?

**Comment by bolds07** [comment]
implementation("com.mercadopago.android.px:checkout:4.6.1") {

**Comment by zehemz** [comment]
@bolds07 this issue has been fixed on 4.6.2 
https://github.com/mercadopago/px-android/compare/4.6.1...4.6.2#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR3

Anyway, we recommend you to use 4.7.2 that is a newer version. 

Soon in 4.8.0 we will reduce the size of our pngs one of the things you ask for.

**Comment by bolds07** [comment]
Is there any real reason to include libstatic-webp.so and libimagepipeline.so?

together they take over 1MB of space and i dont see any real point of them.
I inspect the whole code of this api and there is no mention to webp images... so why include a lib about it? by the way android added support to webp images on API 15 and this api minsdk is 16 so it is TOTTALLY UNECESSARY

libimagepipeline.so i dont know what it does but im quite sure is something the api doesn't use either

to develop a software is more than just import lots of fancy apis, is to have a reason to use them
Lima, Rafael

By the way i still think that this api should fit 1MB to be considered reasonable...
It is not topic of this discursion but the only reason i started using it are: 
1- stripe is not available in brazil yet
2- pagseguro (which is the biggest player in brazil) supports a political party which i'm against...

**Comment by bolds07** [comment]
> @bolds07 this issue has been fixed on 4.6.2
> [4.6.1...4.6.2](https://github.com/mercadopago/px-android/compare/4.6.1...4.6.2)
> 
> Anyway, we recommend you to use 4.7.2 that is a newer version.
> 
> Soon in 4.8.0 we will reduce the size of our pngs one of the things you ask for.

i'm using the 4.10.0 and still the resources are wayyyyyyyyyyy to big

my app without mercadopago api apk 5.0MB
my app with mercadopago api 10.8MB

just twice the size... so if you costumers are just huge app companies with apps larger than 20MB it may be no difference...

if you really want to create a universal api for any developper you are way going in the wrong way...

imagine i create an app for taking photos and charge the users 1 dolar per photo, the app itself would be just few kbs for loading the camera... and 5MB of mercadopago lib it makes NOOOOO SENSE

you are talking about SOUTH AMERICA more than 70% of devices out there are low end devices and have no spare memory and disk to all this stuff my app is 5MB and when i force uses to update i get lots of complain because some people need to delete photos and other apps in order to be able to update

so i'm 90% sure i will delete this api from my app i just want to ask one last time:

IS THERE ANY REAL ESTIMATIVE TO REMOVE THE GARBAGE OUT OF THIS API? 

You have a thousand drawables that are ABSOLUTELLY POINTLESS. who was the genius that had the idea to put every logo from every bank in south america in an api?

just to give you a short hint, the probabillity of someone who has an bank account in brazil (and sees brazilian banks) also have a bank account in colombia (and then see colombian logos) is about 1%

so for every single user that uses this payment system, he will just see 10% of the logos you put into the lib, but he will be forced to load all of them... would be smarter to simple load them from the server...
