### ISSUE TITLE
Fatal Exception: android.view.WindowManager$BadTokenException

### ISSUE THREAD

**Issue by bolds07** [mercadopago/px-android#1605]
I don't use picasso in my app, so it is for sure one more error of mercado pago api
i'm using it for like 3 months and i got at least 20 different crashes due this api

This crash is usually caused by your app trying to display a dialog using a previously-finished Activity as a context. For example, this can happen if an Activity triggers an AsyncTask that tries to display a dialog when it is finished, but the user navigates back from the Activity before the task is completed.
External resources
Android – Displaying Dialogs From Background Threads
Error : BinderProxy@45d459c0 is not valid; is your activity running?

Fatal Exception: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:894)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:337)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:109)
       at com.google.firebase.inappmessaging.display.internal.FiamWindowManager.show(SourceFile:62)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay$5$4.run(SourceFile:422)
       at android.app.Activity.runOnUiThread(Activity.java:6050)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay$5.onSuccess(SourceFile:418)
       at com.squareup.picasso.RequestCreator.into(SourceFile:657)
       at com.google.firebase.inappmessaging.display.internal.FiamImageLoader$FiamImageRequestCreator.into(SourceFile:65)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.loadNullableImage(SourceFile:477)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.inflateBinding(SourceFile:356)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.access$400(SourceFile:82)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay$2.run(SourceFile:292)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by zehemz** [comment]
Hi @bolds07 , the stacktrace clearly shows that the trigger for this event is ```FirebaseInAppMessagingDisplay``` that does not correspond to our module at all. Therefore, we can assume that that google module uses picasso internally.
Have you tried to display the dependency tree in your app module?

The crash you report is not conclusive about being MercadoPago's module bug and it does not have the "caused by" sentence.

Please, try to be more polite with us, we have closed many bugs you reported as soon as possible.
