### ISSUE TITLE
No Such Method Error before startActivityForResult is called

### ISSUE THREAD

**Issue by Renascienza** [mercadopago/px-android#1934]
Some very needed 3rd party libraries on my project uses the updated Picasso, so I can't avoid it.

At final of the payment process I have this error:

`java.lang.NoSuchMethodError: No static method with(Landroid/content/Context;)Lcom/squareup/picasso/Picasso; in class Lcom/squareup/picasso/Picasso; or its super classes (declaration of 'com.squareup.picasso.Picasso' appears in ,,,
        at com.mercadopago.android.px.internal.view.PaymentResultHeader.renderIcon(PaymentResultHeader.java:62)
        at com.mercadopago.android.px.internal.view.PaymentResultHeader.setModel(PaymentResultHeader.java:56)
        at com.mercadopago.android.px.internal.features.payment_result.PaymentResultActivity.configureViews(PaymentResultActivity.java:81)
        at com.mercadopago.android.px.internal.features.payment_result.PaymentResultPresenter.configureView(PaymentResultPresenter.java:139)
        at com.mercadopago.android.px.internal.features.payment_result.PaymentResultPresenter.attachView(PaymentResultPresenter.java:64)
        at com.mercadopago.android.px.internal.features.payment_result.PaymentResultActivity.onCreated(PaymentResultActivity.java:62)
        at com.mercadopago.android.px.internal.base.PXActivity.onCreate(PXActivity.java:24)`

Any solution or workaround?

**Comment by cgaggino** [comment]
Hi Renascienza,

I came with a workaround and I think it could works for you. It was released in 4.27.1 version

Let me know if it helps

Kind regards

**Comment by Renascienza** [comment]
Hi, @cgaggino . The workaround was tested and is successful, the payment process works now.

So many thanks.
