### ISSUE TITLE
implementation 'com.mercadopago.android.px:checkout:4.28.0'

### ISSUE THREAD

**Issue by GastonMelo** [mercadopago/px-android#1977]
I include this line in gradle. Now I got this:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.car_wash_app, PID: 28966
    java.lang.RuntimeException: Unable to instantiate application com.example.app java.lang.ClassNotFoundException: Didn't find class com.example.app.update.class
at android.app.LoadedApk.makeApplication(LoadedApk.java:979)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6036)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6942)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```
If I remove the line in gradle:
implementation 'com.mercadopago.android.px:checkout:4.28.0'

everythong is working again.
Why?
I download the example code and checking the gradle i cant find this line.
I read the installation process on Github but its not working. Any help?

**Comment by guchito9** [comment]
In which device or simulator are you running the app?
Android version and architecture (x86, etc)

https://stackoverflow.com/questions/40546581/java-lang-runtimeexception-unable-to-instantiate-application-classnotfoundexc
