### ISSUE TITLE
Error startPayment (java.lang.BootstrapMethodError: Exception from call site #22 bootstrap methodically)

### ISSUE THREAD

**Issue by viniciusalvesmello** [mercadopago/px-android#2058]
Can you help me with this error?
Below are the codes for the demo application.

Error:
```
2020-03-03 11:19:36.573 9403-9403/br.com.fretebras.testemercadopago E/AndroidRuntime: FATAL EXCEPTION: main
    Process: br.com.fretebras.testemercadopago, PID: 9403
    java.lang.BootstrapMethodError: Exception from call site #22 bootstrap method
        at com.mercadopago.android.px.internal.datasource.DiscountServiceImp.<init>(DiscountServiceImp.java:26)
        at com.mercadopago.android.px.internal.di.Session.getDiscountRepository(Session.java:276)
        at com.mercadopago.android.px.internal.di.Session.getPaymentRepository(Session.java:336)
        at com.mercadopago.android.px.internal.features.checkout.CheckoutActivity.getActivityParameters(CheckoutActivity.java:194)
        at com.mercadopago.android.px.internal.features.checkout.CheckoutActivity.initPresenter(CheckoutActivity.java:102)
        at com.mercadopago.android.px.internal.features.checkout.CheckoutActivity.onCreated(CheckoutActivity.java:86)
        at com.mercadopago.android.px.internal.base.PXActivity.onCreate(PXActivity.java:27)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1293)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3101)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3260)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1976)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6912)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
     Caused by: java.lang.ClassCastException: Bootstrap method returned null
        at com.mercadopago.android.px.internal.datasource.DiscountServiceImp.<init>(DiscountServiceImp.java:26) 
        at com.mercadopago.android.px.internal.di.Session.getDiscountRepository(Session.java:276) 
        at com.mercadopago.android.px.internal.di.Session.getPaymentRepository(Session.java:336) 
        at com.mercadopago.android.px.internal.features.checkout.CheckoutActivity.getActivityParameters(CheckoutActivity.java:194) 
        at com.mercadopago.android.px.internal.features.checkout.CheckoutActivity.initPresenter(CheckoutActivity.java:102) 
        at com.mercadopago.android.px.internal.features.checkout.CheckoutActivity.onCreated(CheckoutActivity.java:86) 
        at com.mercadopago.android.px.internal.base.PXActivity.onCreate(PXActivity.java:27) 
        at android.app.Activity.performCreate(Activity.java:7144) 
        at android.app.Activity.performCreate(Activity.java:7135) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1293) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3101) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3260) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1976) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6912) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860) 
```

MainActivity.kt
```kotlin
package br.com.fretebras.testemercadopago

import android.app.Activity
import android.content.Intent
import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import com.mercadopago.android.px.core.MercadoPagoCheckout
import com.mercadopago.android.px.model.Payment
import com.mercadopago.android.px.model.exceptions.MercadoPagoError
import kotlinx.android.synthetic.main.activity_main.*


class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        btStartMercadoPagoCheckout.setOnClickListener {
            startMercadoPagoCheckout()
        }
    }

    fun startMercadoPagoCheckout() {
        MercadoPagoCheckout.Builder(
            "xxxxxxxxx",
            "xxxxxxxxx"
        ).build().startPayment(this, REQUEST_CODE)
    }

    override fun onActivityResult(
        requestCode: Int,
        resultCode: Int,
        data: Intent?
    ) {
        super.onActivityResult(requestCode, resultCode, data)

        if (requestCode == REQUEST_CODE) {
            val message: String = when {
                resultCode == MercadoPagoCheckout.PAYMENT_RESULT_CODE -> {
                    val payment =
                        data?.getSerializableExtra(MercadoPagoCheckout.EXTRA_PAYMENT_RESULT) as? Payment
                    "Resultado del pago: ${payment?.paymentStatus}"
                }
                resultCode == Activity.RESULT_CANCELED && (data?.extras?.containsKey(
                    MercadoPagoCheckout.EXTRA_ERROR
                ) ?: false) -> {
                    val mercadoPagoError =
                        data?.getSerializableExtra(MercadoPagoCheckout.EXTRA_ERROR) as? MercadoPagoError
                    "Error: ${mercadoPagoError?.message}"
                }
                else -> {
                    "Pagamento Cancelado"
                }
            }
            mp_results.text = message
        }
    }

    companion object {
        const val REQUEST_CODE = 1
    }
}
```

File app/src/main/res/layout/activity_main.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android='http://schemas.android.com/apk/res/android'
    xmlns:tools='http://schemas.android.com/tools'
    android:layout_width='match_parent'
    android:layout_height='match_parent'
    android:paddingLeft='16dp'
    android:paddingRight='16dp'
    android:paddingTop='16dp'
    android:paddingBottom='16dp'
    android:orientation='vertical'
    tools:context='.MainActivity'>
    <LinearLayout
        android:id="@+id/mpsdkRegularLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

        <Button
            android:id="@+id/btStartMercadoPagoCheckout"
            android:layout_width='match_parent'
            android:layout_height='50dp'
            android:layout_marginTop='25dp'
            android:gravity='center'
            android:text='Pagar $10'/>

        <TextView
            android:layout_width='match_parent'
            android:layout_height='wrap_content'
            android:id='@+id/mp_results'
            android:paddingTop='50dp'/>
    </LinearLayout>
</FrameLayout>
````

File app/build.gradle
```gradle
apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.2"
    defaultConfig {
        applicationId "br.com.fretebras.testemercadopago"
        minSdkVersion 21
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.core:core-ktx:1.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'

    implementation 'com.mercadopago.android.px:checkout:4.36.0'
}
```

**Comment by cgaggino** [comment]
Hi @viniciusalvesmello, have you tried adding java 1.8 to your gradle config? like this

compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

Hope it was helpful

**Comment by cgaggino** [comment]
Closed by error, we will wait to know if it work

**Comment by cgaggino** [comment]
I think that kotling should have something like this

kotlinOptions {
    jvmTarget = "1.8"
}

**Comment by viniciusalvesmello** [comment]
Thanks! This solved it!
Sorry for the delay to return.
