### ISSUE TITLE
java.lang.NullPointerException at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:111)

### ISSUE THREAD

**Issue by viniciusalvesmello** [mercadopago/px-android#2060]
With the sandbox, I was unable to complete the payment.
Log show this error, but app no crash.
Does anyone know why this happens?

```
2020-03-03 22:06:13.570 18510-18510/bt.com.fretebras.testemercadopago W/Calligraphy: Can't create asset from null. Make sure you have passed in the correct path and file name.
    java.lang.NullPointerException
        at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:111)
        at android.graphics.Typeface.createFromAsset(Typeface.java:831)
        at uk.co.chrisjenx.calligraphy.TypefaceUtils.load(TypefaceUtils.java:35)
        at com.mercadolibre.android.ui.font.CalligraphyTypefaceSetter.createTypeface(CalligraphyTypefaceSetter.java:41)
        at com.mercadolibre.android.ui.font.CalligraphyTypefaceSetter.setTypeface(CalligraphyTypefaceSetter.java:19)
        at com.mercadolibre.android.ui.font.TypefaceHelper.setTypeface(TypefaceHelper.java:45)
        at com.mercadopago.android.px.internal.font.FontHelper.setFont(FontHelper.java:57)
        at com.mercadopago.android.px.internal.view.MPTextView.<init>(MPTextView.java:34)
        at com.mercadopago.android.px.internal.view.MPTextView.<init>(MPTextView.java:23)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.view.View.inflate(View.java:24372)
        at com.mercadopago.android.px.internal.view.AmountView.init(AmountView.java:76)
        at com.mercadopago.android.px.internal.view.AmountView.<init>(AmountView.java:56)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
        at com.mercadopago.android.px.internal.features.payment_vault.PaymentVaultActivity.setContentView(PaymentVaultActivity.java:154)
        at com.mercadopago.android.px.internal.features.payment_vault.PaymentVaultActivity.onCreated(PaymentVaultActivity.java:118)
        at com.mercadopago.android.px.internal.base.PXActivity.onCreate(PXActivity.java:27)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1293)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3101)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3260)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1976)
2020-03-03 22:06:13.571 18510-18510/bt.com.fretebras.testemercadopago W/Calligraphy:     at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6912)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)

```

![image](https://user-images.githubusercontent.com/5225560/75835137-d51dc200-5d9c-11ea-97c9-4b83d3c2167f.png)

**Comment by cgaggino** [comment]
Hi! 

The stacktrace is not related to rejected payment, is a problem with a font that is try catched and does not produce any crash nor undesired behaviour.

To help you with the error we are going to need more info, what lib's version are you using? all credentials are from sandbox? can you share the preference id to check it? when did you do the payment? so we can check our logs. To sum up, anything you can share to us will help

**Comment by viniciusalvesmello** [comment]
Using the card available in the documentation (https://www.mercadopago.com.br/developers/pt/guides/payments/web-payment-checkout/test-integration#bookmark_cart%C3%B5es_de_teste), I managed to solve. Thank you for your help.
