### ISSUE TITLE
Error al crear la compra

### ISSUE THREAD

**Issue by NeriCodec** [mercadopago/px-android#2176]
Anexo el log del error:

```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Failure delivering result ResultInfo{who=null, request=65839, result=-1, data=null} to activity {mx.com.inteek.gp.test/com.mercadopago.android.px.internal.features.review_and_confirm.ReviewAndConfirmActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.mercadopago.android.px.model.PaymentMethod.getPaymentTypeId()' on a null object reference
System.err: 
System.err: StackTrace:
System.err: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=65839, result=-1, data=null} to activity {mx.com.inteek.gp.test/com.mercadopago.android.px.internal.features.review_and_confirm.ReviewAndConfirmActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.mercadopago.android.px.model.PaymentMethod.getPaymentTypeId()' on a null object reference
System.err: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5471)
System.err: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5512)
System.err: 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
System.err: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
System.err: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:107)
System.err: 	at android.os.Looper.loop(Looper.java:213)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8178)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.mercadopago.android.px.model.PaymentMethod.getPaymentTypeId()' on a null object reference
System.err: 	at com.mercadopago.android.px.internal.datasource.PaymentService.getPaymentDataList(PaymentService.java:312)
System.err: 	at com.mercadopago.android.px.internal.callbacks.PaymentServiceHandlerWrapper.handleEsc(PaymentServiceHandlerWrapper.java:179)
System.err: 	at com.mercadopago.android.px.internal.callbacks.PaymentServiceHandlerWrapper.onPaymentError(PaymentServiceHandlerWrapper.java:170)
System.err: 	at com.mercadopago.android.px.internal.datasource.PaymentService.checkPaymentMethod(PaymentService.java:214)
System.err: 	at com.mercadopago.android.px.internal.datasource.PaymentService.startPayment(PaymentService.java:206)
System.err: 	at com.mercadopago.android.px.internal.datasource.PaymentService$1.success(PaymentService.java:193)
System.err: 	at com.mercadopago.android.px.internal.datasource.PaymentService$1.success(PaymentService.java:170)
System.err: 	at com.mercadopago.android.px.internal.datasource.cache.InitMemCache.resolve(InitMemCache.java:32)
System.err: 	at com.mercadopago.android.px.internal.datasource.cache.InitMemCache$1.enqueue(InitMemCache.java:20)
System.err: 	at com.mercadopago.android.px.internal.datasource.PaymentService.startExpressPayment(PaymentService.java:170)
System.err: 	at com.mercadopago.android.px.internal.features.pay_button.PayButtonViewModel$startPayment$1.success(PayButtonViewModel.kt:115)
System.err: 	at com.mercadopago.android.px.internal.features.pay_button.PayButton$Handler$-CC.$default$enqueueOnExploding(PayButton.kt:35)
System.err: 	at com.mercadopago.android.px.internal.features.review_and_confirm.ReviewAndConfirmActivity.enqueueOnExploding(Unknown Source:0)
System.err: 	at com.mercadopago.android.px.internal.features.pay_button.PayButtonViewModel.startPayment(PayButtonViewModel.kt:113)
System.err: 	at com.mercadopago.android.px.internal.features.pay_button.PayButtonViewModel.handleBiometricsResult(PayButtonViewModel.kt:101)
System.err: 	at com.mercadopago.android.px.internal.features.pay_button.PayButtonFragment.onActivityResult(PayButtonFragment.kt:144)
System.err: 	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:170)
System.err: 	at com.mercadopago.android.px.internal.features.review_and_confirm.ReviewAndConfirmActivity.onActivityResult(ReviewAndConfirmActivity.java:99)
System.err: 	at android.app.Activity.dispatchActivityResult(Activity.java:8413)
System.err: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5464)
System.err: 	... 11 more
```

**Comment by NeriCodec** [comment]
Arreglado, estaba relacionado a esto: #2175
