### ISSUE TITLE
Error with marketplace payment

### ISSUE THREAD

**Issue by fedefa** [mercadopago/px-android#2179]
Hola, el error sucede luego de crear la preference.

MercadoPagoCheckout
                .Builder(publicKey, checkoutPreferenceId)
                .build()
                .startPayment(context!!, MP_CHECKOUT_REQUEST_CODE)
    }

Parámetros: 
publicKey: publickKey obtenida al autenticar al vendedor con https://api.mercadopago.com/oauth/token
checkoutPreferenceId: Creada con un payer (distinto al usuario del vendedor, usuario de prueba tmb) y un marketplace_fee y los datos del producto.

No esta claro si se puede usar de esta manera, usando la publick key del vendedor pero el flujo del front funciona bien hasta el último paso  donde el "Pagar" falla pero sin errores en la consola. Solo sale el SnackBar rojo sin texto desde abajo.

Hay algun error en la implementación? Hay otra manera de implementar el marketplace desde android?
Gracias!

**Comment by fedefa** [comment]
Visa de Argentina, con nombre "APRO". De las que se listan acá: https://www.mercadopago.com.ar/developers/es/guides/marketplace/web-checkout/testing-marketplace/

**Comment by fedefa** [comment]
No hay nada no. Lo único que veo relevante es esto, que no es un error:

`2020-06-04 12:37:59.238 925-2708/? I/ActivityTaskManager: START u0 {cmp=com.prebocorp.prebo.stagingv2/com.mercadopago.android.px.addons.internal.MockValidationActivity} from uid 10119
`
Te envio el logcat igual por si ves algo:


`2020-06-04 12:36:18.345 1461-2121/? I/chatty: uid=10043(com.android.systemui) pool-6-thread-1 identical 4 lines
2020-06-04 12:36:19.560 1461-2121/? D/PowerUI: can't show warning due to - plugged: true status unknown: false
2020-06-04 12:36:20.050 925-2905/? I/ActivityTaskManager: START u0 {cmp=com.prebocorp.prebo.stagingv2/com.mercadopago.android.px.addons.internal.MockValidationActivity} from uid 10119
2020-06-04 12:36:19.533 672-672/? I/chatty: uid=1000(system) health@2.0-serv identical 3 lines
2020-06-04 12:36:19.860 672-672/? I//vendor/bin/hw/android.hardware.health@2.0-service.marlin: SRAM data: 2812000
2020-06-04 12:36:20.051 676-676/? D/QCOM PowerHAL: LAUNCH HINT: ON
2020-06-04 12:36:20.054 676-676/? D/QCOM PowerHAL: Activity launch hint handled
2020-06-04 12:36:20.065 12892-17002/com.prebocorp.prebo.stagingv2 V/FA: Recording user engagement, ms: 36367
2020-06-04 12:36:20.068 12892-17002/com.prebocorp.prebo.stagingv2 V/FA: Connecting to remote service
2020-06-04 12:36:20.074 12892-12892/com.prebocorp.prebo.stagingv2 W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@b8ac52a
2020-06-04 12:36:20.083 12892-17002/com.prebocorp.prebo.stagingv2 V/FA: Activity paused, time: 169028185
2020-06-04 12:36:20.088 12892-12892/com.prebocorp.prebo.stagingv2 V/FA: onActivityCreated
2020-06-04 12:36:20.101 12892-17002/com.prebocorp.prebo.stagingv2 D/FA: Logging event (FE): user_engagement(_e), Bundle[{ga_event_origin(_o)=auto, engagement_time_msec(_et)=36367, ga_screen_class(_sc)=ReviewAndConfirmActivity, ga_screen_id(_si)=4222634316581160682}]
2020-06-04 12:36:20.145 12892-17002/com.prebocorp.prebo.stagingv2 V/FA: Connection attempt already in progress
2020-06-04 12:36:20.146 12892-17002/com.prebocorp.prebo.stagingv2 V/FA: Activity resumed, time: 169028263
2020-06-04 12:36:20.165 12892-17002/com.prebocorp.prebo.stagingv2 V/FA: Connection attempt already in progress
2020-06-04 12:36:20.165 12892-17002/com.prebocorp.prebo.stagingv2 D/FA: Connected to remote service
2020-06-04 12:36:20.167 12892-17002/com.prebocorp.prebo.stagingv2 V/FA: Processing queued up service tasks: 3
2020-06-04 12:36:20.179 676-676/? D/QCOM PowerHAL: LAUNCH HINT: OFF
2020-06-04 12:36:20.205 2280-17005/? V/FA-SVC: Logging event: origin=auto,name=user_engagement(_e),params=Bundle[{ga_event_origin(_o)=auto, engagement_time_msec(_et)=36367, ga_screen_class(_sc)=ReviewAndConfirmActivity, ga_screen_id(_si)=4222634316581160682}]
2020-06-04 12:36:20.234 2280-17005/? V/FA-SVC: Upload scheduled in approximately ms: 534799
2020-06-04 12:36:20.234 2280-17005/? V/FA-SVC: Unscheduling upload
2020-06-04 12:36:20.237 2280-17005/? V/FA-SVC: Scheduling upload, millis: 534799
2020-06-04 12:36:20.240 2280-17005/? V/FA-SVC: Background event processing time, ms: 35
2020-06-04 12:36:20.264 2058-16400/? E/SQLiteDatabase: Error inserting flex_time=534000 job_id=-1 period=1070000 source=16 requires_charging=0 preferred_network_type=1 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService user_id=0 target_package=com.google.android.gms tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG task_type=0 required_idleness_state=0 service_kind=0 source_version=201817000 persistence_level=1 preferred_charging_state=1 required_network_type=0 runtime=1591284980248 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}} last_runtime=0
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067 SQLITE_CONSTRAINT_UNIQUE)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:879)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:88)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1599)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1468)
        at apiz.a(:com.google.android.gms@201817037@20.18.17 (120400-311416286):78)
        at apio.a(:com.google.android.gms@201817037@20.18.17 (120400-311416286):196)
        at apio.a(:com.google.android.gms@201817037@20.18.17 (120400-311416286):20)
        at apio.a(:com.google.android.gms@201817037@20.18.17 (120400-311416286):190)
        at apex.run(:com.google.android.gms@201817037@20.18.17 (120400-311416286):8)
        at sfd.b(:com.google.android.gms@201817037@20.18.17 (120400-311416286):12)
        at sfd.run(:com.google.android.gms@201817037@20.18.17 (120400-311416286):7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at sld.run(:com.google.android.gms@201817037@20.18.17 (120400-311416286):0)
        at java.lang.Thread.run(Thread.java:919)
2020-06-04 12:36:20.730 12892-16938/com.prebocorp.prebo.stagingv2 W/prebo.stagingv: Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
2020-06-04 12:36:20.732 12892-16938/com.prebocorp.prebo.stagingv2 W/FirebaseRemoteConfig: No value of type 'String' exists for parameter key 'sessions_max_length_minutes'.
2020-06-04 12:36:20.732 12892-17006/com.prebocorp.prebo.stagingv2 W/FirebaseRemoteConfig: No value of type 'String' exists for parameter key 'sessions_feature_enabled'.
2020-06-04 12:36:20.733 12892-17006/com.prebocorp.prebo.stagingv2 W/prebo.stagingv: Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
2020-06-04 12:36:20.734 12892-17006/com.prebocorp.prebo.stagingv2 W/prebo.stagingv: Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
2020-06-04 12:36:20.735 12892-17006/com.prebocorp.prebo.stagingv2 W/prebo.stagingv: Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
2020-06-04 12:36:21.168 672-672/? I//vendor/bin/hw/android.hardware.health@2.0-service.marlin: SRAM data: 2812000
`

**Comment by guchito9** [comment]
Tiene pinta de ser un problema con las credenciales, que public key y pref id estás usando?

**Comment by fedefa** [comment]
Esta es la publick key del vendedor, junto con los datos de las responses más abajo:

```
        val preferenceId = "579398857-5c8e4b89-6f5d-4915-8a91-66641024b694" //Created by seller"
        val sellerPublicKey = "TEST-9a69ddfc-eecc-46b2-b2fc-d59f0d946d5d"
```

`{
  "access_token": "TEST-6886682360471875-060414-4f120faa56d92b00d2cac8380206d0a5-579398857",
  "public_key": "TEST-9a69ddfc-eecc-46b2-b2fc-d59f0d946d5d",
  "refresh_token": "TG-5ed90addc056e000067ed992-579398857",
  "live_mode": false,
  "user_id": 579398857,
  "token_type": "bearer",
  "expires_in": 15552000,
  "scope": "offline_access read write"
}`

Y esta la preference:


`{"additional_info":"","auto_return":"","back_urls":{"failure":"","pending":"","success":""},"binary_mode":false,"client_id":"6886682360471875","collector_id":579398857,"coupon_code":null,"coupon_labels":null,"date_created":"2020-06-04T15:11:01.795+00:00","expiration_date_from":null,"expiration_date_to":null,"expires":false,"external_reference":"","id":"579398857-5c8e4b89-6f5d-4915-8a91-66641024b694","init_point":"https://www.mercadopago.com.ar/checkout/v1/redirect?pref_id=579398857-5c8e4b89-6f5d-4915-8a91-66641024b694","internal_metadata":null,"items":[{"id":"nuevo","category_id":"","currency_id":"ARS","description":"MultiItem","title":"Otro","quantity":1,"unit_price":10}],"marketplace":"MP-MKT-6886682360471875","marketplace_fee":2,"metadata":{},"notification_url":null,"operation_type":"regular_payment","payer":{"phone":{"area_code":"","number":""},"address":{"zip_code":"","street_name":"","street_number":null},"email":"test_user_85194061@testuser.com","identification":{"number":"","type":""},"name":"","surname":"","date_created":null,"last_purchase":null},"payment_methods":{"default_card_id":null,"default_payment_method_id":null,"excluded_payment_methods":[{"id":""}],"excluded_payment_types":[{"id":""}],"installments":1,"default_installments":null},"processing_modes":null,"product_id":null,"redirect_urls":{"failure":"","pending":"","success":""},"sandbox_init_point":"https://sandbox.mercadopago.com.ar/checkout/v1/redirect?pref_id=579398857-5c8e4b89-6f5d-4915-8a91-66641024b694","site_id":"MLA","shipments":{"default_shipping_method":null,"receiver_address":{"zip_code":"","street_name":"","street_number":null,"floor":"","apartment":"","city_name":null,"state_name":null,"country_name":null}},"total_amount":null,"last_updated":null}ode":"","street_name":"","street_number":null,"floor":"","apartment":"","city_name":null,"state_name":null,"country_name":null}},"total_amount":null,"last_updated":null}`

**Comment by fedefa** [comment]
Muchas gracias! Dame un rato que pruebo entonces y te aviso.

**Comment by guchito9** [comment]
Estoy haciendo pruebas y me parece que hay un tema con los users de test. Probando con las keys sandbox de un usuario real y no de test parece andar todo bien

**Comment by fedefa** [comment]
Si gracias por la ayuda, con usuarios reales también me anduvo el pago. Hay un problema con los usuarios de prueba entonces. Te quería consultar donde puedo ver si se aplico el fee y el pago en el marketplace. En https://applications.mercadopago.com.ar/list?platform=mp solo aparecen los detalles básicos. Y en la pantalal principal del usuario (como lo cree con mi usuario personal)no aparece ninguna información del marketplace.

**Comment by William-ST** [comment]
Buenas tardes, soy de Perú y tengo el mismo error **Snackbar Rojo pero no muestra ningún mensaje de error**, en mi caso este error se da cuando se hace un pago utilizando la opción de transferencia o usando pago efectivo **en producción**, en el ambiente de desarrollo si se puede generar la información para realizar la transferencia (o código en pagoefectivo) y va bien. He enviado varias consultas a través de su página de ayuda pera ya van 5 días y no recibo respuesta alguna.

Podrían apoyarme por favor, estoy usando el sdk android mobile checkout 4.51.0 (pagos por tarjeta si funcionan, el problema es con transferencias y pago efectivo).

Gracias!

**Comment by cgaggino** [comment]
Hola @fedefa, te comento que el sdk no funciona como marketplace, no lo tenemos en un roadmap cercano tampoco pero no descartamos incluirlo, procedo a cerrar el ticket pero podes abrir otro en caso de que necesites mas ayuda!

Hola @William-ST seguimos tu caso en el ticket que abriste https://github.com/mercadopago/px-android/issues/2235

**Comment by maueli** [comment]
Hola yo soy de Argentina, y tambien tengo el mismo problema, pero tanto con usuarios TEST como con usuarios Verdaderos. Alguno sabe porque ocurre?

**Comment by Pulpogrammer** [comment]
> Buenas,@cgaggino Alguna fecha estimada de cuando van a soportar el marketplace_fee en el sdk? ¿Alguna solución? Gracias

Pudiste resolverlo?
