### ISSUE TITLE
Attempts to integrate your project into my build fail altogether

### ISSUE THREAD

**Issue by webargus** [mercadopago/px-android#2513]
I've been trying to integrate mercado pago into my Android project through https://jitpack.io/#mercadopago/px-android/ , but unfortunately it hasn't worked for me so far. As indicated in the jitpack.io website, I included
```
allprojects {
  repositories {
	...
	maven { url 'https://jitpack.io' }
  }
}
```
in my gradle.build file and added
```
dependencies {
    implementation 'com.github.mercadopago:px-android:Tag'
}
```
to my Gradle app file, replacing the Tag with your top release versions (from 4.82.0 to 4.79.0), but all attempts returned errors.
Last, I tried release 4.53.1, but then again got an error:

> Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.github.mercadopago:px-android:4.53.1.

Furthermore, following your advice and including
`implementation 'com.mercadopago.android.px:checkout:4.+`
instead, I could actually integrate the checkout successfully, but it only works in debug mode!
Any attempt to build my code in release mode throws the following exception:

> Could not determine the dependencies of task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugAndroidTestCompileClasspath'.
   > **Could not find org.jetbrains.kotlin:kotlin-stdlib:1.3.0-rc-57**.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.3.0-rc-57/kotlin-stdlib-1.3.0-rc-57.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.3.0-rc-57/kotlin-stdlib-1.3.0-rc-57.pom
       - https://jitpack.io/org/jetbrains/kotlin/kotlin-stdlib/1.3.0-rc-57/kotlin-stdlib-1.3.0-rc-57.pom
     Required by:
         project :app > **com.github.mercadopago:px-android:4.53.1** > **com.github.mercadopago.px-android:services:4.53.1** > com.jakewharton.retrofit:retrofit2-kotlin-coroutines-adapter:0.9.2
   > Could not find org.jetbrains.kotlin:kotlin-stdlib:1.3.0-rc-57.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.3.0-rc-57/kotlin-stdlib-1.3.0-rc-57.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.3.0-rc-57/kotlin-stdlib-1.3.0-rc-57.pom
       - https://jitpack.io/org/jetbrains/kotlin/kotlin-stdlib/1.3.0-rc-57/kotlin-stdlib-1.3.0-rc-57.pom
     Required by:
         project :app > **com.github.mercadopago:px-android:4.53.1** > **com.github.mercadopago.px-android:services:4.53.1** > com.jakewharton.retrofit:retrofit2-kotlin-coroutines-adapter:0.9.2 > org.jetbrains.kotlinx:kotlinx-coroutines-core:0.26.1-eap13
   > Could not find org.jetbrains.kotlin:kotlin-stdlib-common:1.3.0-rc-51.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-stdlib-common/1.3.0-rc-51/kotlin-stdlib-common-1.3.0-rc-51.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-common/1.3.0-rc-51/kotlin-stdlib-common-1.3.0-rc-51.pom
       - https://jitpack.io/org/jetbrains/kotlin/kotlin-stdlib-common/1.3.0-rc-51/kotlin-stdlib-common-1.3.0-rc-51.pom
     Required by:
         project :app > **com.github.mercadopago:px-android:4.53.1** > **com.github.mercadopago.px-android:services:4.53.1** > com.jakewharton.retrofit:retrofit2-kotlin-coroutines-adapter:0.9.2 > org.jetbrains.kotlinx:kotlinx-coroutines-core:0.26.1-eap13 > org.jetbrains.kotlinx:kotlinx-coroutines-core-common:0.26.1-eap13
         project :app > **com.github.mercadopago:px-android:4.53.1** > **com.github.mercadopago.px-android:services:4.53.1** > com.jakewharton.retrofit:retrofit2-kotlin-coroutines-adapter:0.9.2 > org.jetbrains.kotlinx:kotlinx-coroutines-core:0.26.1-eap13 > org.jetbrains.kotlinx:kotlinx-coroutines-core-common:0.26.1-eap13 > org.jetbrains.kotlinx:atomicfu-common:0.11.7-eap13

> Possible solution:
> - Declare repository providing the artifact, see the documentation at  > https://docs.gradle.org/current/userguide/declaring_repositories.html

, which seems to indicate that artifact 
`org.jetbrains.kotlin:kotlin-stdlib:1.3.0-rc-57`
is missing, but then again my attempts to include it failed consistently and I believe the artifact must be included in your build rather than in my project.
Sorry for the rather extensive description, but I've been struggling with this issue for a couple days now and I would hugely appreciate if you could help me, please!
Many thanks!

**Comment by webargus** [comment]
Hi there,
I found (partially) what I was doing wrong; I replaced gradle 'implementation' with 'releaseImplementation' and managed to compile release 4.75.0 with
`releaseImplementation "com.github.mercadopago:px-android:4.75.0"`
but now I'm getting a runtime crash:
> 2021-07-06 20:44:32.813 6007-6007/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.webargus.standardapp, PID: 6007
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.mercadopago.android.px.internal.features.express.ExpressPaymentPresenter.getCurrentOneTapItem(ExpressPaymentPresenter.java:260)
        at com.mercadopago.android.px.internal.features.express.ExpressPaymentPresenter.updateElements(ExpressPaymentPresenter.java:334)
        at com.mercadopago.android.px.internal.features.express.ExpressPaymentPresenter.loadViewModel(ExpressPaymentPresenter.java:218)
        at com.mercadopago.android.px.internal.features.express.ExpressPaymentPresenter.initPresenter(ExpressPaymentPresenter.java:234)
        at com.mercadopago.android.px.internal.features.express.ExpressPaymentPresenter.attachView(ExpressPaymentPresenter.java:228)
        at com.mercadopago.android.px.internal.features.express.ExpressPaymentFragment.onViewCreated(ExpressPaymentFragment.java:244)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1971)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:311)
        at com.mercadopago.android.px.internal.features.checkout.CheckoutActivity.showOneTap(CheckoutActivity.java:191)
        at com.mercadopago.android.px.internal.features.checkout.CheckoutPresenter.showOneTap(CheckoutPresenter.java:79)
        at com.mercadopago.android.px.internal.features.checkout.CheckoutPresenter$1.success(CheckoutPresenter.java:59)
        at com.mercadopago.android.px.internal.features.checkout.CheckoutPresenter$1.success(CheckoutPresenter.java:56)
        at com.mercadopago.android.px.internal.datasource.CheckoutRepositoryImpl$1$1.success(CheckoutRepositoryImpl.java:153)
        at com.mercadopago.android.px.internal.datasource.CheckoutRepositoryImpl$1$1.success(CheckoutRepositoryImpl.java:149)
        at com.mercadopago.android.px.internal.adapters.ErrorHandlingCallAdapter$MPCallAdapter$1.lambda$onResponse$0(ErrorHandlingCallAdapter.java:75)
        at com.mercadopago.android.px.internal.adapters.-$$Lambda$ErrorHandlingCallAdapter$MPCallAdapter$1$GT1fTaFtHjux92wi9aWYccW6wYk.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6666)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)

Any ideas why?
Thx!
