### ISSUE TITLE
Unable to get provider com.mercadopago.android.px.internal.di.PxCheckoutInitProvider

### ISSUE THREAD

**Issue by alemdg** [mercadopago/px-android#2516]
Aplicacion HelloWorld.

Compila.
Corre en emulalor y explota con el siguiente error:

**java.lang.RuntimeException: Unable to get provider com.mercadopago.android.px.internal.di.PxCheckoutInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.mercadopago.android.px.internal.di.PxCheckoutInitProvider"**

log:

2021-07-08 09:50:55.521 14270-14270/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.myapplication, PID: 14270
    java.lang.RuntimeException: Unable to get provider com.mercadopago.android.px.internal.di.PxCheckoutInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.mercadopago.android.px.internal.di.PxCheckoutInitProvider" on path: DexPathList[[zip file "/data/app/com.example.myapplication-XmZpYSkgC-b4-asnSe4imQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.myapplication-XmZpYSkgC-b4-asnSe4imQ==/lib/x86, /data/app/com.example.myapplication-XmZpYSkgC-b4-asnSe4imQ==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:6288)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5851)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5772)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

`
import com.mercadopago.android.px.core.MercadoPagoCheckout;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Toolbar toolbar = findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        FloatingActionButton fab = findViewById(R.id.fab);
        fab.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {

                new MercadoPagoCheckout.Builder("xxxxxxxxxxxxxxxxxxxxxxx", "yyyyyyyyyyyyyyyyyyyy")
                        .build()
                        .startPayment(MainActivity.this , 123);
            }
        });
    }
`

**Comment by alemdg** [comment]
11 dias
