### ISSUE TITLE
com.mercadopago.android.px.internal.di.NetworkModule.getSessionIdProvider NPE

### ISSUE THREAD

**Issue by jotapeg** [mercadopago/px-android#2745]
When trying to instantiate `com.mercadopago.android.px.services.MercadoPagoServices` on version 4.53.2 a NullPointerException is thrown. Detailed stacktrace below:
```
09-20 18:59:49.494: E/AndroidRuntime(14306): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.mercadopago.android.px.internal.core.SessionIdProvider com.mercadopago.android.px.internal.di.NetworkModule.getSessionIdProvider()' on a null object reference
09-20 18:59:49.494: E/AndroidRuntime(14306): at com.mercadopago.android.px.internal.util.HttpClientUtil.createBaseClient(HttpClientUtil.java:91)
09-20 18:59:49.494: E/AndroidRuntime(14306): at com.mercadopago.android.px.internal.util.HttpClientUtil.getClient(HttpClientUtil.java:60)
09-20 18:59:49.494: E/AndroidRuntime(14306): at com.mercadopago.android.px.internal.util.RetrofitUtil.getRetrofit(RetrofitUtil.java:33)
09-20 18:59:49.494: E/AndroidRuntime(14306): at com.mercadopago.android.px.internal.util.RetrofitUtil.getRetrofitClient(RetrofitUtil.java:20)
09-20 18:59:49.494: E/AndroidRuntime(14306): at com.mercadopago.android.px.services.MercadoPagoServices.<init>(MercadoPagoServices.java:69)
```
It seems `NetworkModule.INSTANCE` field has not been initialized yet. Should I be explicitly calling `NetworkModule.initialize(context: Context)` before instantiating `MercadoPagoServices` or is this just a bug?

**Comment by guchito9** [comment]
Hi, thanks for the report, we'll check it

**Comment by jotapeg** [comment]
Just to confirm, I manually initialized `NetworkModule.INSTANCE` field through its `initialize(context: Context)` method as I previously mentioned and everything worked fine as before. Thanks.

**Comment by guchito9** [comment]
That's good but you don't have to do that so maybe there is a problem in the library
