### ISSUE TITLE
Mercadopago.CL, StringIndexOutOfBoundsException al dar click a "webpay" o "servipag"

### ISSUE THREAD

**Issue by christiansalazar** [mercadopago/px-android#306]
Estimados, estoy obteniendo una excepción cuando se le hace click al botón de Webpay o Servipag. Con el botón de CreditCard no da problema.

Cómo reproducir, en una app nueva, poner un botón de pago, darle click y cuando aparezca la actividad darle click a webpay o servipag.
```
public void onClickPagar(View view){
            new MercadoPago.StartActivityBuilder()
                .setActivity(this)
                .setPublicKey("TEST-0b549f99-3e52-49c0-9cbb-552dc8d2673c")
                .setCheckoutPreferenceId("227920209-1cb3d866-93f6-461c-9ff6-d840ee52f85c")
                .startCheckoutActivity();
...
}
```

`01-15 17:49:04.249 19289-19289/cl.chileshift.android.mercadopagoconandroid E/AndroidRuntime: FATAL EXCEPTION: main
Process: cl.chileshift.android.mercadopagoconandroid, PID: 19289
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=10, result=-1, data=Intent { (has extras) }} to activity {cl.chileshift.android.mercadopagoconandroid/com.mercadopago.CheckoutActivity}: java.lang.StringIndexOutOfBoundsException: length=6; regionStart=0; regionLength=-1
 at android.app.ActivityThread.deliverResults(ActivityThread.java:4927)
 at android.app.ActivityThread.handleSendResult(ActivityThread.java:4970)
 at android.app.ActivityThread.access$1600(ActivityThread.java:223)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1851)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:158)
 at android.app.ActivityThread.main(ActivityThread.java:7231)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
**********Caused by: java.lang.StringIndexOutOfBoundsException: length=6; regionStart=0; regionLength=-1**************
 at java.lang.String.startEndAndLength(String.java:298)
 at java.lang.String.substring(String.java:1087)
 at com.mercadopago.util.CurrenciesUtil.getSpannedString(CurrenciesUtil.java:98)
 at com.mercadopago.util.CurrenciesUtil.formatCurrencyInText(CurrenciesUtil.java:129)
 at com.mercadopago.util.CurrenciesUtil.formatCurrencyInText(CurrenciesUtil.java:120)
 at com.mercadopago.uicontrollers.reviewandconfirm.ReviewSummaryView.getFormattedAmount(ReviewSummaryView.java:168)
 at com.mercadopago.uicontrollers.reviewandconfirm.ReviewSummaryView.drawSummary(ReviewSummaryView.java:111)
 at com.mercadopago.CheckoutActivity.drawSummary(CheckoutActivity.java:647)
 at com.mercadopago.CheckoutActivity.showReviewAndConfirm(CheckoutActivity.java:630)
 at com.mercadopago.CheckoutActivity.resolvePaymentVaultRequest(CheckoutActivity.java:473)
 at com.mercadopago.CheckoutActivity.onActivityResult(CheckoutActivity.java:427)
 at android.app.Activity.dispatchActivityResult(Activity.java:7138)
 at android.app.ActivityThread.deliverResults(ActivityThread.java:4923)
 at android.app.ActivityThread.handleSendResult(ActivityThread.java:4970) 
 at android.app.ActivityThread.access$1600(ActivityThread.java:223) 
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1851) 
 at android.os.Handler.dispatchMessage(Handler.java:102) 
 at android.os.Looper.loop(Looper.java:158) 
 at android.app.ActivityThread.main(ActivityThread.java:7231) 
 at java.lang.reflect.Method.invoke(Native Method) 
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) `

**Comment by christiansalazar** [comment]
Hola @mreverter , hay noticias sobre este caso ? no he vuelto a probar, pero esto detuvo la decisión de usar mercadopago, no esta descartado, solo detenido hasta nuevo reintento :)

**Comment by zehemz** [comment]
En V4 el botón de pago ha sido deprecado.
Recomendamos migrar a v4
